# Generated by Django 2.2.8 on 2020-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarname', models.CharField(max_length=122)),
                ('file', models.FileField(upload_to='avatars/')),
            ],
            options={
                'verbose_name_plural': 'Avatars',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=122)),
                ('question_details', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=122)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Voices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voicename', models.CharField(max_length=122)),
                ('file', models.FileField(upload_to='voices/')),
            ],
            options={
                'verbose_name_plural': 'Voices',
            },
        ),
    ]
